laboratorio4/config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :monstruos
  
  root 'tweets#default'
end

laboratorio4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

laboratorio4/app/models/monstruo.rb
class Monstruo < ApplicationRecord
  has_many :tweets, dependent: :destroy

  default_scope -> { order :nombre }
end

laboratorio4/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :monstruo

end

laboratorio4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

laboratorio4/app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
  end

  def show
    @monstruo = Monstruo.find(params[:id])
    if @monstruo.tweets.count>1
      @tweets = @monstruo.tweets.all
    else
      redirect_to monstruos_path, notice:"FALOPAAAAAAAAAAAAAAa"##Si leen esto y piensan q esta mal, chupenme un uevo
      #Para hacer q te muestre en rojo tenes q agregar bootsrap y hacer un par d cosas mas link: https://www.youtube.com/watch?v=jB6UXLsInUA
    end
  end

  def edit    
  end
  
  def destroy
    @monstruo = Monstruo.find(params[:id])
    if @monstruo.destroy
      redirect_to monstruos_path, notice: "NO CHINCHULIN QUE HICISTE"
    end
  end
end

laboratorio4/app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def new
  	@tweet = Tweet.new
  end

  def default    
  end
  
  def index
    @tweets = Tweet.all

  end

  def show
  end

  # -----------------
  # CREATE
  # El método create recibe params = { tweet: { monstruo_id: valor, estado: valor } }
  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:monstruo_id,:estado))
    if @tweet.save
      redirect_to tweets_path, notice: "nuebo twit"
    else
      flash[:error] = "SALAMEEEEE"
      render :new
    end
  end
end

laboratorio4/app/helpers/application_helper.rb
module ApplicationHelper
end

laboratorio4/app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag "logo.png", title: "Logo", class: "logo" %>
        <% end %>
      </div>
      <div class="collapse navbar-collapse">
        
      </div><!--/.nav-collapse -->
    </div>

  </div>
</header>

laboratorio4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laboratorio4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"> 
  
      <% if flash[:notice] %>
        <div class="alert alert-info"> <%= flash[:notice] %> </div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

laboratorio4/app/views/monstruos/edit.html.erb
<h1> Editar monstruo </h1>

<p> No está hecho </p>

laboratorio4/app/views/monstruos/index.html.erb
<h1> Listado de Monstruos </h1>
<table class="table">

	<tr>
		<th> Nombre </th>
		<th> Descripción </th>
		<th> Critter start </th>
		<th> Acciones </th>
	</tr>

	<% monstruos = Monstruo.all %>
	<% monstruos.each do |monstruo| %>
		<tr>
			<td> <%= link_to monstruo.nombre, monstruo %> </td>
			<td> <%= monstruo.descripcion %> </td>
			<td> <%= (monstruo.critter_star) ? 'Si' : 'No' %> </td>
			<td>
				<%= link_to "Editar", edit_monstruo_path(monstruo), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar", monstruo, method: :delete, class: 'btn btn-danger btn-sm' %>
			</td>
		</tr>
	<% end %>

	<% if monstruos.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

laboratorio4/app/views/monstruos/show.html.erb
<!DOCTYPE html>
<html>
    <title>
        ASD
    </title>
    <body>
        <h1>
            <%=@monstruo.nombre%><%=image_tag "logo.png"%>
       </h1>
       <p>
           <%=@monstruo.descripcion%>
       </p>
       <%@tweets.each do |tweet|%>
       <li>
           <ul>
                <%=tweet.estado%>
           </ul>
       </li>
       <%end%>
    </body>
</html>

laboratorio4/app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

laboratorio4/app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nuevo Tweet", new_tweet_path %></li>
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>  
</ul>

laboratorio4/app/views/tweets/index.html.erb
<!-- Listado de tweets -->
<!DOCTYPE html>
<html>
    <head> <title> Tweets </title> </head>
    <body>
        <table>
            <tr>
                <th> Estado </th>
                <th> Monstruo </th>
            </tr>
            <% @tweets.each do |tweet| %>
            <tr>
                <td> <%= tweet.estado %> </td>
                <td> <%= tweet.monstruo.nombre %> </td>
            </tr>
            <% end %>
        </table>
    </body>
</html>

laboratorio4/app/views/tweets/new.html.erb
<div class="container">
	<h1> Crear un tweet para un monstruo </h1>

	<%= form_for @tweet do |f| %>
		
		<div class="row">
			<div class="col-md-4">
				<%= f.label :monstruo_id, 'Monstruo' %>
  				<%= collection_select(:tweet, :monstruo_id, Monstruo.all, :id, :nombre, {}, { class: 'form-control'}) %>
  			</div>
  		</div>


		<div class="row">
			<div class="col-md-6">
				<%= f.label :estado %>
  				<%= f.text_area :estado, class: 'form-control', label: 'Estado', placeholder: 'Ingrese el estado' %>
  			</div>
  		</div>

  		<%= f.submit "Crear tweet", class: 'btn btn-primary' %>
  	</div>
<% end %>
</div>

laboratorio4/app/views/tweets/show.html.erb
<!-- Ver un tweet -->
Detalle del tweet