laboratorio3/config/routes.rb
Rails.application.routes.draw do
 get 'monstruos/index'

  get 'monstruos/show'

  resources :tweets
  resources :monstruos do
    collection do
      get 'ver'
    end
  end
  
  root 'tweets#default'
end

laboratorio3/app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
  has_many :tweets
end

laboratorio3/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :monstruo
end

laboratorio3/app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
  end

  def show
  end
  
  def ver    
  end
  
  def destroy
    monstruo = Monstruo.find(params[:id])
    monstruo.destroy
    redirect_to monstruos_path
  end
  
end

laboratorio3/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def default
  end
  
  def index
  end

  def show
  end

end

laboratorio3/app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
                 
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </header>

laboratorio3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Critter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"> 
      <%= yield %>
    <end>
  </body>
</html>

laboratorio3/app/views/monstruos/index.html.erb
<!------------------------------------------------------ 
Acá va a ir el listado de monstruos usando los tags  
<ul> y <li>.
Debe tener un título y mostrar el nombre (en negrita) y
la descripción.
------------------------------------------------------>

<!DOCTYPE html>
<html>
    <head>
        <%= stylesheet_link_tag 'application', media: 'all'%>
    </head>
    <title>
        ASD
    </title>
    <body>

            <%Monstruo.all.each do |monstruo|%>
            <ul>
                <li>
                    <%=link_to(monstruo.nombre,monstruo)%> 
                    <%if (monstruo.tweets.count>1)%>
                    <b class="tw">Twittero destacado</b>
                    <%end%>
                    : <b><%=monstruo.descripcion%></b> <%=link_to("Borrar",monstruo,method: :delete,class:"btn btn-danger")%>
                </li>
            </ul>
            <%end%>
    </body>
</html>

laboratorio3/app/views/monstruos/show.html.erb
<!DOCTYPE html>
<html>
    <title>
        ASD
    </title>
    <body>
        <%monstruo=Monstruo.find(params[:id])%>
        <h1>
            <%=monstruo.nombre%><%=image_tag "logo.png"%>
       </h1>
       <p>
           <%=monstruo.descripcion%>
       </p>
    </body>
</html>

laboratorio3/app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

<!DOCTYPE html>
<html>
    
    <head>
        <title>
          Falopa
        </title>
    </head>
    <body>
        <%monstruo=Monstruo.first%>
         <h1>
             <%=monstruo.nombre%>
        </h1>
        <p>
            <%=monstruo.descripcion%>
        </p>
    </body>
</html>

laboratorio3/app/views/tweets/default.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="row">
      <div class="col-xs-12 col-md-10"><h1> Bienvenido a Critter </h1>
          <h3> ¿Qué desea hacer? </h3></div>
    </div>
    <div class="container-fluid">
      <div class="row">  
        <ul>
          <div class="col-md-6">
            Sexo porno anal
          </div>
          <div class="col-md-6">
              <li> 
                <%= link_to "Listado de Monstruos", monstruos_path %>
              </li>
              <li>
                <%= link_to "Ver el primer monstruo", ver_monstruos_path %>
              </li>
          </div>
        </ul>
      </div>
    </div>
  </body>
</html>

laboratorio3/app/views/tweets/index.html.erb
<!-- Listado de tweets -->

laboratorio3/app/views/tweets/show.html.erb
<!-- Ver un tweet -->